Meet-Coder-Study/posting-review

- shldhee/200622/SkillOfCoding_Javascript(#5-2).md
> 자바스크립트 코딩의 기술 5장 정리(2/2)

- sanghwanAN/2020-07-16-css-gird-template.md
지난 주에 작성한 포스팅인데 브런치가 조금 꼬여서 새로운 브런치에
피드백 반영하여 다시 pull request 합니다.
> [css] grid 포스팅04 (gird로 리스트배열하기-02)

- SeYunKim/2020-07-16-lombok-1.md
한번에 정리하려고 하니깐, 예상외로 많은 어노테이션이 존재하네요...ㅎㅎㅎ
다음에 끝내는 방향으로 가겠습니다!
Close #91
> [#91] Lombok 사용법 1 (XXXArgsConstructor, Getter, Setter, ToString)

- paduckk/Firebase_function_tips_tricks.md
> udpate firebase function tips & tricks

- shldhee/200723/2020-07-23-skill-of-coding-javascript#8-1.md
> [#101] 자바스크립트 코딩의 기술 8장 정리(1탄)

- shldhee/200723/2020-07-23-skill-of-coding-javascript#8-1.md
- shldhee/200728/2020-07-28-skill-of-coding-javascript#8-2.md
> [#115] 자바스크립트 코딩의 기술 8장 정리(#2)

- choisohyun/2020-08-13-dark-mode.md
> [#146] [React + TS + styled-component] 다크모드 적용하기

- hyein/2020-07-30-optional.md
> [#113] Optional 기초

- SeYunKim/2020-08-31-value-configurationproperties-yaml.md
> @Value, @ConfigurationProperties를 이용해 ymal 파일 매핑하기 (#164)

- pkch93/2020-09-03-woowa-tech-learning.md
우아한 테크러닝 3기 2일차 내용입니다~!
이번주까지 업무 + 이사 일정 때문에 학습한게 이게 전부네요,,,
다음주부터는 다시 달리도록 할께요..!
closed #173
> [#173] 자바스크립트 함수와 바닐라자바스크립트로 리덕스 구현해보기

- SeYunKim/2020-08-31-value-configurationproperties-yaml.md
- SeYunKim/2020-09-07-spring-boot-tests.md
> [#175] 스프링 부트 테스트 종류들

- SeYunKim/2020-08-31-value-configurationproperties-yaml.md
- SeYunKim/2020-09-07-spring-boot-tests.md
- SeYunKim/2020-09-17-logback-profile-combination.md
> [#186] Spring Logback Profile 조합 전략

- choisohyun/2020-09-17-context-api-vs-redux.md
요즘 정신이 없어서 급하게 썼네요 ㅠㅠ  
Close #191
> [#191][React] Context API 와 Redux 비교하기 작성

- hyeinkim/2020-09-18-JPA 일대 다 관계.md
> [#197]일대 다 관계

- SeYunKim/2020-09-30-logback-slack-appender.md
- SeYunKim/2020-10-07-sonarqube-apply-java.md
> [#238] 정적분석도구 소나큐브 적용기 😂

- hyeinkim/2020-10-08-기본 키 생성 전략.md
> [#237] JPA 기본 키 생성 전략

- SeYunKim/2020-10-15-blue-green-deployment.md
resolve #256 
면접때문에 멘탈이 나가서 내용이 많이 부실하네요..ㅠㅠ
피드백주시면 열심히... 추가해나가겠습니다. 궁금하신거 다 물어보세요!
> [#256] Blue/Green 무중단 배포를 진행해보자.(Spring Boot + Nginx)

- sungikchoi/2020-10-15-window-is-not-available.md
저번 포스팅을 마무리하고 싶었는데 개발중 문제가 발생해서, 마무리되면 완벽한 코드로 그 때 수정하려고 합니다.
이번주는 정신없어서 포스팅이 짧네요
close #266
> [#266] 빌드 에러 "window is not available..." 해결법

- hyeinkim/2020-10-15-JUnit5 시작하기.md
정신 없는 한 주 였네요.. 간단히 정리만 했습니다,,
시간이 되면 더 보완해서 올릴게요🤙
resolved: #264
> [#264] JUnit5 시작하기

- cwpark/spring/2020-10-22-spring-autoconfigure.md
> [#278] 스프링 자동구성

- ChoiJunSung/2020-10-22-typescript-basic.md
- ChoiJunSung/2020-11-05-javascript-todo-list.md
> [#269] Typescript 기본 개념

- hyeinkim/2020-11-05-linux-commandline-search.md
> [#301]리눅스 명령어 정리-검색

- ChoiJunSung/2020-11-05-javascript-todo-list.md
> [#309] Javascript Todolist 만들어보기

- naeun/2020-11-12_JS_methods.md
resolve #315 
proxy에 대해서는 공부하면서 토요일 전까지 좀 더 추가해 보도록 할게요! 
자바스크립트 스터디하면서 자주 사용하지만 약간 헷갈렸던 메서드 위주로 정리해보았습니다.  잘부탁드립니당!
> [#315] JavaScript의 메소드와 기능 정리

- hyeinkim/2020-11-12-AssertJ 시작하기.md
> [#326]AssertJ 시작하기

- rockjoon/2020-11-19-effective-java-item7/2020-11-19-effective-java-item7.md
> [#336] 이펙티브자바 아이템 7. 다 쓴 객체 참조를 해제하라.

- cwpark/java/2020-11-10-Java8-Lambda-Functional-Interface.md
> [#333] Java 8 람다와 함수형 인터페이스

- pkch93/2020-12-04-spring-boot-image-build.md
> [#356] Spring Boot Image Build

- cwpark/java/2020-12-03-java-fork-join-framework.md
자바 포크 조인 프레임워크입니다. 
이걸 이용해 다양한 프로그램을 짜보고 싶네요.
close #358
> [#358] Java fork/join framework

- hyeinkim/2020-11-12-AssertJ 시작하기.md
- hyeinkim/2020-12-03-File.md
> [#361]java File

- SeYunKim/2020-12-07-mvc-pattern.md
> [#366] MVC Pattern이란?

- SeYunKim/2020-12-17-solid.md
> [#378] 객체지향 설계를 위한 SOLID 원칙

- hyeinkim/2020-12-31-REST-API.md
> [#384]그런 REST API로 괜찮은가

- SeYunKim/2021-01-06-cohesion-vs-coupling.md
> [#427] 응집도 vs 결합도

- pkch93/2020-01-14-higher-order-function.md
> [#444] 고차함수

- SeYunKim/2021-01-13-string-stringbuilder-stringbuffer.md
> [#446] String vs StringBuilder vs StringBuffer

- rockjoon/2021-01-21-Objects.requireNonNull/2021-01-21-Objects.requireNonNull.md
[바로보기](https://github.com/Blog-Posting/posting-review/blob/b05e4d245f829d45395d5abdb0a43c1cb61e498f/rockjoon/2021-01-21-Objects.requireNonNull/2021-01-21-Objects.requireNonNull.md)
closed #464
> [#463]Object.requireNonNull

- eunbeen/2021-1-21-React_Router_SPA.md
> [#471] 리액트 라우터로 SPA 개발하기

- rockjoon/2021-02-04-expression/expression.md
[이동 버그](https://github.com/Meet-Coder-Study/posting-review/blob/1b7e4c516d53ff239da4b8830fc6c1bb6f0cc2c9/rockjoon/2021-02-04-expression/expression.md)
closed #492
> expression에 관한 재미있는 사실들

- naeun/2021-02-10-정적팩토리메소드.md
> [#509] 정적 팩토리 메소드(static factory method)

- jiaekim/2021-02-11-rest-api-2.md
closed #490 
[바로보기 링크](https://github.com/jiaekim123/posting-review/blob/master/jiaekim/2021-02-11-rest-api-2.md)
> [#490] [REST API의 이해와 설계] 2.REST API 디자인 가이드

- SeYunKim/2021-02-12-submodule-config.md
> [#525] git 서브모듈 설정하기

- LeeJungHyeok/2020-02-18-SpringDI.md
> [#536] Spring DI 

- SeYunKim/2021_02_18_active_record_basics.md
> [#541] Ruby On Rails Active Record Basics

- rockjoon/2021-02-25-lazy-evaluation/2021-02-25-lazy-evaluation.md
> [#531] Lazy evaluation

- pkch93/2021-03-11-reactor.md
> [#579] reactor

- naeun/2021-03-09_토큰,쿠키세션2.md
> [#563] 토큰 인증방식(+ 쿠키,세션 추가내용)

- byungwoo/2021-03-11-kubernetes-objects.md
close #585 
[편하게 보기](https://github.com/Meet-Coder-Study/posting-review/blob/byungwoo/byungwoo/2021-03-11-kubernetes-objects.md)
> [#585] Kubernetes Objects

- LeeJungHyeok/2021-03-12-kotlin-base-1.md
> [#592] Kotlin 기본 1

- pkch93/2021-03-20-reactor-scheduler.md
> [#600] reactor scheduler

- jiaekim/2021-03-18-grpc.md
close #608 
[미리보기](https://github.com/jiaekim123/posting-review/blob/master/jiaekim/2021-03-18-grpc.md)
> [#608] gRPC 초안

- pkch93/2021-03-25-reactor-advanced.md
> [#615] reactor advanced

- LeeJunGyun/2021-04-11-spring-querydslPagingItemReader.md
spring-batch QuerydslPagingItemReader 설명
> [4기][2주차] spring-batch QuerydslPagingItemReader 설명

- pkch93/2021-04-15-curl.md
curl에 대해 간단히 알아보았습니다.
curl과 관련한 꿀팁이 있으시다면 공유해주셔도 좋을거 같아요 ㅎㅅㅎ
> [4기][2주차] curl

- yewon/2021-04-15-db-lock.md
MySQL 기반의 DB LOCK 기능에 대해 알아봤습니다 😄 
더 다채롭게 채울 수 있도록 리뷰 통해 도움을 주시면 감사하겠습니다! 🙏
> [4기][2주차] MYSQL DB LOCK

- byungwoo/2021-04-22-system-config.md
[편하게 보기](https://github.com/Meet-Coder-Study/posting-review/blob/byungwoo/byungwoo/2021-04-22-system-config.md)
> [4기][3주차] 시스템 구성 정보 확인하기

- jangchulwoom/2021-04-15-kotlin-companion.md
- jangchulwoom/2021-04-22-kotlin-scope-function.md
[편하게 보기](https://github.com/Meet-Coder-Study/posting-review/blob/7410812a7c13e126cc5970c367a8e043fe92cbd1/jangchulwoom/2021-04-22-kotlin-scope-function.md)
kotlin scope function 을 정리해봤습니다. :) 
~@ksy90101  님 cherry pick 하나 부탁드릴게요 ㅠㅠ (_ _)~
마지막 파일만 봐주세요 ..!
> [4기][3주차][kotlin] scope function

- yun/2021-04-15-spring-gateway.md
- yun/2021-04-22-ktlint.md
[Kotlin Ktlint](https://github.com/cheese10yun/posting-review/blob/master/yun/2021-04-22-ktlint.md)
> [4기][3주차] Ktlint 코드 스타일 검사

- jiaekim/2021-04-22-git-search.md
[바로보기](https://github.com/Meet-Coder-Study/posting-review/blob/dea240ee8091d965487a3763778f84c73ee41f38/jiaekim/2021-04-22-git-search.md)
회사 코드를 염탐하다가 알게된 깨알같은 깃헙 검색 지식들..
> [4기][3주차] github 똑똑하게 검색하기

- yun/2021-04-29-spring-kotlin.md
[Spring with kotlin](https://github.com/cheese10yun/posting-review/blob/master/yun/2021-04-29-spring-kotlin.md)
> [4기][4주차] Spring With Kotlin

- LeeJunGyun/2021-04-28-spring data jpa save 동작 원리.md
> [4기][4주차] Jpa save 동작 원리 정리

- jiaekim/2021-04-30-nosql-mongo.md
[편하게보기](https://github.com/Meet-Coder-Study/posting-review/blob/d6ffee0f9d7f34c250929c7ae81a559c50301fe0/jiaekim/2021-04-30-nosql-mongo.md)
(몽고디비를 포스팅하려 했는데 어느샌가 내용은 NoSQL이 되어있었다.)
> [4기][4주차] NoSQL

- jangchulwoom/2021-04-29-kotlin-cookbook2.md
[편하게보기](https://github.com/Meet-Coder-Study/posting-review/blob/6d90f53d9987ce8ed6c35713de1ad5c13a864fda/jangchulwoom/2021-04-29-kotlin-cookbook2.md)
> [4기][4주차][kotlin] cookbook 2장

- LeeJunGyun/2021-05-06-spring data jpa save vs saveAll 비교.md
> [4기][5주차] spring data jpa save, saveAll 비교

- yewon/2021-05-06-gitops.md
GitOps에 대해서 알아봤습니다 :D
다음 주엔 시리즈로 pull 타입의 operator개념이나 github actions를 통한 push 타입의 gitops 설정방법에 대해 알아볼까 합니다.
> [4기][5주차]GitOps : git을 기반으로 하는 자동화된 infrastructure system

- LeeJunGyun/2021-05-13-transaction 동작원리.md
[4기][6주차] spring transaction 동작 원리
> [4기][6주차] spring transaction 동작 원리

- jangchulwoom/2021-05-13-kotlin-cookbook3.md
[편하게 보기](https://github.com/Meet-Coder-Study/posting-review/blob/f83113cd88bdf54152c7f7f12211c3345c8703a2/jangchulwoom/2021-05-13-kotlin-cookbook3.md)
> [4기][6주차] kotlin cookbook 3장

- yun/2021-05-13-docker-mysql-replication.md
[Docker Mysql Replication 구성하기](https://github.com/cheese10yun/posting-review/blob/master/yun/2021-05-13-docker-mysql-replication.md)
> [4기][6주차] Docker Mysql Replication 구성하기

- yun/2021-05-20-exposed.md
[Exposed](https://github.com/cheese10yun/posting-review/blob/master/yun/2021-05-20-exposed.md)
> [4기][7주차] Exposed  ORM 프레임워크 정리

- byungwoo/2021-05-13-golang.md
- byungwoo/2021-05-20-dirty-page.md
[편하게 보기](https://github.com/Meet-Coder-Study/posting-review/blob/byungwoo/byungwoo/2021-05-20-dirty-page.md)
> [4기][7주차] dirty page가 I/O에 미치는 영향

- LeeJunGyun/2021-05-20-spring data jpa batch insert 정리.md
[4기][7주차] spring data jpa batch insert 정리
> [4기][7주차] spring data jpa batch insert 정리

- LeeJunGyun/2021-05-27-spring data jpa batch insert 정리.md
> [4기][8주차] 저번에 올린 spring-data-jpa batch insert 내용 추가

- jangchulwoom/2021-06-03-mock-reset-service.md
최근 장애대응으로 .. 예전에 정리해둔 글을 살짝 다시 정리했습니다 (_ _) 
[편하게보기](https://github.com/Meet-Coder-Study/posting-review/blob/851da5c1ffefc136ed7f2f17ea0e3245221c0230/jangchulwoom/2021-06-03-mock-reset-service.md)
> [4기][9주차] [test] mockRestService

- yun/2021-06-05-spring-batch-reader-performance.md
[링크](https://github.com/cheese10yun/posting-review/blob/master/yun/2021-06-05-spring-batch-reader-performance.md)
> [4기][9주차] Batch Reader 성능 분석

- LeeJunGyun/2021-06-03-전각, 반각 문자 정리.md
> [4기][9주차] 전각, 반각 문자 정리

- pkch93/2021-06-03-auto-params.md
테스트 데이터 자동 생성 라이브러리인 AutoParams에 대해 알아보았습니다.
테스트 데이터를 만들고 관리하는 것에 고민이 많았는데 AutoParams의 Customization 방식이 꽤 유용해 보이네요.
혹시 다른분들은 테스트 데이터를 어떻게 생성/관리하실까요?
> [4기][9주차] JavaUnit AutoParams

- byungwoo/2021-05-27-docker-compose.md
- byungwoo/2021-06-92-ansible.md
- [편하게 보기](https://github.com/Meet-Coder-Study/posting-review/blob/byungwoo/byungwoo/2021-06-92-ansible.md)
> [4기][9주차] Ansible로 시작하는 IaC

- yun/2021-07-08-jpa-jpql.md
[바로 보기](https://github.com/cheese10yun/posting-review/blob/master/yun/2021-07-08-jpa-jpql.md)
하지만 다 이유가 있었다. 오해해서 미안해 JPA
> [김남윤] JPA는 왜 그러는 것일까?

- LeeJunGyun/2021-07-08-spring message converter.md
[이준균] spring message converter 설명
[바로보기](https://github.com/leechoongyon/posting-review/blob/LeeJunGyun/LeeJunGyun/2021-07-08-spring%20message%20converter.md)
> [이준균] spring message converter 설명

- heowc/2021-07-22-elasticache-maintenance.md
[바로보기](https://github.com/heowc/posting-review/blob/master/heowc/2021-07-22-elasticache-maintenance.md)
> [5기][허원철] ElastiCache maintenance

- GuMinGyu/2021-07-22-data-fetching-library.md
Data fetching library가 탄생하게된 배경과 장점
> [5기][구민규] Data fetching library

- yun/2021-07-08-jpa-jpql.md
- yun/2021-07-22-elk-apm-1.md
[살펴보기](https://github.com/cheese10yun/posting-review/blob/master/yun/2021-07-22-elk-apm-1.md)
> [5기][김남윤] Elasticsearch APM 1편

- yewon/2021-07-29-RIOT-API-DISCORD-BOT.md
> [5기][강예원]RIOT API를 활용하는 discord bot 개발하기(1)

- LeeJunGyun/2021-07-28-spring batch jpa multi datasource, transaction 정리.md
[미리보기](https://github.com/leechoongyon/posting-review/blob/LeeJunGyun/LeeJunGyun/2021-07-28-spring%20batch%20jpa%20multi%20datasource%2C%20transaction%20%EC%A0%95%EB%A6%AC.md)
> [5기][이준균] spring batch jpa multi datasource, transaction 정리

- yun/2021-08-01-spring-config-server.md
[편하게 보기](https://github.com/cheese10yun/posting-review/blob/master/yun/2021-08-01-spring-config-server.md)
> [5기][김남윤] Config Server

- jiaekim/2021-08-13-gradle.md
[편하게 보기](https://github.com/jiaekim123/posting-review/blob/master/jiaekim/2021-08-13-gradle.md)
[코멘트 남기기](https://github.com/Meet-Coder-Study/posting-review/pull/809/files)
> [5기][김지애] gradle

- LeeJunGyun/2021-08-11-spring rest doc 정리.md
[5기][이준균] spring rest doc 정리
[편하게 보기](https://github.com/leechoongyon/posting-review/blob/LeeJunGyun/LeeJunGyun/2021-08-11-spring%20rest%20doc%20%EC%A0%95%EB%A6%AC.md)
> [5기][이준균] spring rest doc 정리

- yun/2021-08-19-config-client.md
[Cloud Config & Cloud Bus 정리 카프카를 이용한 Config 변경사항 전파](https://github.com/cheese10yun/posting-review/blob/master/yun/2021-08-19-config-client.md)
> [5기][김남윤] Cloud Config & Cloud Bus 카프카를 이용한 Config 변경사항 전파

- rockjoon/2021-08-19-reducing-the-number-of-parameters.md
[바로보기](https://github.com/Meet-Coder-Study/posting-review/blob/de5daf10bf81203af8b1aabc769e0ceb46408a7f/rockjoon/2021-08-19-reducing-the-number-of-parameters.md)
> [5기][최락준] 파라미터 수 줄이기

- LeeJunGyun/2021-08-26-spring transactional readOnly 정리.md
[편하게 보기](https://github.com/leechoongyon/posting-review/blob/LeeJunGyun/LeeJunGyun/2021-08-26-spring%20transactional%20readOnly%20%EC%A0%95%EB%A6%AC.md)
> [5기][이준균] spring transactional readonly 정리

- donghwan/java/2021-08-26-volatile.md
[편하게보기](https://github.com/DongHwani/posting-review/blob/master/donghwan/java/2021-08-26-volatile.md)
> [5기][김동환] 자바 - volatile

- yun/2021-09-04-test-code.md
[보기](https://github.com/cheese10yun/posting-review/blob/master/yun/2021-09-04-test-code.md)
> [5기][김남윤] 테스트 코드에 대한 고찰

- byungwoo/2021-09-09-ansible-techniques.md
- [편하게 보기](https://github.com/bart2001/posting-review/blob/byungwoo/byungwoo/2021-09-09-ansible-techniques.md)
> [5기][이병우] 미리 알았으면 좋을 Ansible 테크닉들

- pkch93/2021-10-28-redis-pubsub.md
[편하게 보기](https://github.com/Meet-Coder-Study/posting-review/pull/865/files?short_path=ac35079#diff-ac350793ca9816fea00f212d49525e641e836f4221b101d6131f5501ab8b6bde)
> [박경철] Redis PubSub

- changsub/-JPA- 연관관계 매핑 기초.md
[바로보기](https://github.com/brido4125/posting-review/blob/fdf98d5650ca7819144d1d6c030820201bd9f3a2/changsub/-JPA-%20%EC%97%B0%EA%B4%80%EA%B4%80%EA%B3%84%20%EB%A7%A4%ED%95%91%20%EA%B8%B0%EC%B4%88.md)
> [홍창섭]JPA 연관관계 매핑 기초

- jiaekim/2021-11-02-hystrix.md
[편하게보기](https://github.com/jiaekim123/posting-review/blob/master/jiaekim/2021-11-02-hystrix.md)
> [김지애] Hystrix Circuit Breaker 파헤치기

- cwpark/web/2021-11-04-HTTP-status-code.md
[읽기](https://github.com/Meet-Coder-Study/posting-review/blob/448ce3525d37d1514096e49a95235afabdf82929/cwpark/web/2021-11-04-HTTP-status-code.md)
> [박창원] HTTP 상태 코드

- pkch93/2021-11-11-architectures.md
[get your hands dirty on clean architecture](http://www.yes24.com/Product/Goods/87753198)의 1장, 2장을 읽고 정리한 글입니다. 
다양한 의견이 있을거 같은데 자유롭게 남겨주시면 좋을거 같습니다.
[편하게 보기](https://github.com/Meet-Coder-Study/posting-review/pull/878/files?short_path=2f438e8#diff-2f438e8b21667b57cc069d8eaec9ca604c19a5c2a94af23b8646d5b7f78883a9)
> [박경철] layered architecture와 hexagonal architecture

- kimmingeor/2021-11-13-masking.md
[바로보기](https://github.com/cmg1411/posting-review/blob/master/kimmingeor/2021-11-13-masking.md)
> [김민걸] kotlin과 에너테이션으로 마스킹하기

- LeeJungHyeok/2021-11-27-why-failed-mybatis.md
[mybatis는 어려운것 같습니다는 여기서 보면 편합니다.](https://github.com/Ramen6315/posting-review/blob/why_i_failed_mybatis/LeeJungHyeok/2021-11-27-why-failed-mybatis.md)
> [이중혁] 나는 왜 Mybatis를 어려워 할까

- yun/2021-12-11-string-manipulation.md
[보기](https://github.com/cheese10yun/posting-review/blob/master/yun/2021-12-11-string-manipulation.md)
> [김남윤] 인텔리제이 플러그인 String Manipulation

- pkch93/2022-02-17-valid-validated.md
저번 6기 회고가 12월 27일이었네요 ㅎㅎ 2달만이라 새롭네요
잘부탁드립니당 :)
[편하게보기](https://github.com/Meet-Coder-Study/posting-review/pull/927/files?short_path=56b25fb#diff-56b25fb70fd8230ca11ba6d4fee35a28d71dcfef272133b0a4e2ae226446403e)
> [박경철] Spring Validation - Valid, Validated의 동작

- hyoungJune/2022-02-18-SpringWebflux란?-7기-1week.md
[보기](https://github.com/Flamme1004K/posting-review/blob/1week/hyoungJune/2022-02-18-SpringWebflux%EB%9E%80%3F-7%EA%B8%B0-1week.md)
> [김형준] SpringWebFlux 구경하기 - 1편 SpringWebFlux 란?

- KimDoubleB/2022-02-25_Ephemeral_Container에_대하여.md
[편하게 보기](https://github.com/Meet-Coder-Study/posting-review/blob/fb995305c8d44634b1d1f3b5ee51356313c2cac7/KimDoubleB/2022-02-25_Ephemeral_Container%EC%97%90_%EB%8C%80%ED%95%98%EC%97%AC.md)
이전에 좀 불성실하게 정리했던 부분이라 다시 찾아보며 작성해봤습니다.
그냥 궁금해서 찾아봤던 건데, 아직 사용을 적극적으로 사용해보지는 않아서... 다음엔 더 재미있는 주제로 작성해봐야겠네요 😂
첫 참여인데, 잘 부탁드립니다 :)
> [7기][김보배] Ephemeral Container 에 대하여

- minseok/2022-02-23-DSM.md
IntelliJ에 있는 좋은 툴들에 대해서 글을 써보려고 했는데 그동안 잘 써오던 DSM에 대해서 많은 분들게 소개시켜드리고 싶어서 글을 쓰게 되었네요.
> [7기][김민석] Dependency Structure Matrix

- yun/2022-03-01-http-client.md
[HTTP Client 책임 분리하기](https://github.com/cheese10yun/posting-review/blob/master/yun/2022-03-01-http-client.md)
HTTP Client에 국한되는 내용은 아니며 인프라스트럭처에 대한 계층을 비지니스 및 서비스 계증과 명확하게 분리하고 책임과 역할을 분배하는 패턴이라고 보시면 좋을거 같습니다.
> [7기][김남윤] HTTP Client 책임 분리하기

- pkch93/2022-03-03-package-lock-json.md
좀 더 정리할 부분이 있는데 내일 시간이 되면 좀더 정리해서 올려놓을께요~
[편하게 보기](https://github.com/Meet-Coder-Study/posting-review/pull/953/files?short_path=ee1ec56#diff-ee1ec56173d2b9af58e9419354d2ede7b2de23079133c846d3333672e8629a29)
> [7기][박경철] package-lock.json

- kwanghoon/2022-03-19_Microservice_communication_patterns.md
MSA 패턴에 대한 좋은 글이 있어 번역해보았습니다. 
[편하게 보기](https://github.com/Wave1994-Hoon/posting-review/blob/master/kwanghoon/2022-03-19_Microservice_communication_patterns.md)
> [7기][김광훈] Microservice communication patterns

- pkch93/2022-03-18-java-test-fixtures.md
~~아니 ;; 트리 표현한게 다 깨지네요;; 밋업 전에는 수정해둘께요~~ 수정했습니다.
[편하게 보기](https://github.com/Meet-Coder-Study/posting-review/pull/968/files?short_path=bda87da#diff-bda87da5cbef69850ed3d6dfa0b48cb948214f353999e0967ecfd46cc393684d)
> [7기][박경철] java-test-fixtures

- KimMinSeong/2022-03-25_Java14_Review.md
자바 12 ~ 14까지의 변경된 사항을 정리해보았습니다.
[편하게보기](https://github.com/MINS99/posting-review/blob/KimMinSeong/KimMinSeong/2022-03-25_Java14_Review.md)
> [7기][김민성] Java14까지의 변화

- SeYunKim/2022-04-01-what_fragments.md
> [7기][김세윤] <> Fragments? </>란?

- hyoungJune/2022-04-01_elasticsearch function_score(전체 데이터 스코어에 대한 글)_week7.md
[미리보기](https://github.com/Flamme1004K/posting-review/blob/week4/hyoungJune/2022-04-01_elasticsearch%20function_score(%EC%A0%84%EC%B2%B4%20%EB%8D%B0%EC%9D%B4%ED%84%B0%20%EC%8A%A4%EC%BD%94%EC%96%B4%EC%97%90%20%EB%8C%80%ED%95%9C%20%EA%B8%80)_week7.md)
> [7기][김형준] elasticsearch function_score(전체 데이터 스코어에 대한 글)

- KimMinSeong/2022-04-07_Find_Java_Exception.md
자바는 언제쯤 마스터 할 수 있을까요...
요즘 참여하고 있는 이직 스터디에서 멘토님이 모르는 게 있다면 전부 코드로 작성해보라는 조언을 주셨는데,
마침 스터디에서 나온 얘기가 있어 직접 해본 후기입니다 ㅎㅎ
매번 이론에 대한 발표만 해온것 같아서 쉬어가는 타임으로 최대한 재미있게(?) 작성해보았습니다!
[편하게보기](https://github.com/MINS99/posting-review/blob/KimMinSeong/KimMinSeong/2022-04-07_Find_Java_Exception.md)
> [7기][김민성] 제목은 자바 오류를 찾아서 라고 하겠습니다. 근데 이제 면접 준비를 곁들인

- kwanghoon/2022-04-16_Describe-Context-It-pattern-test.md
[편하게보기](https://github.com/Wave1994-Hoon/posting-review/blob/week9_hoon/kwanghoon/2022-04-16_Describe-Context-It-pattern-test.md)
> [7기] [김광훈]  Describe - Context - It 테스트

- pkch93/2022-04-14-websocket-tomcat.md
문제가 해결되면서 어떤점이 바꼈는지까지 보고 싶은데 이부분은 내일 시간이 되면 정리해볼께요.
[편하게 보기](https://github.com/Meet-Coder-Study/posting-review/pull/997/files?short_path=ed005b2#diff-ed005b26b10fd7f8f37f1ffb1694806711f729cd0f3c442e7a73f7bacb408eda)
> [7기][박경철] Tomcat Websocket 사용시 memory leak 이슈

- hyeinkim/2022-04-16-kotlin-spring.md
당근마켓 밋업 #살아있다 #자프링외길12년차 #코프링2개월생존기를 정리한 내용입니다.
> [7기][김혜인] #살아있다 #자프링외길12년차 #코프링2개월생존기 정리

- hyoungJune/2022-04-15_Kotest란?_week9.md
[미리보기](https://github.com/Flamme1004K/posting-review/blob/week4/hyoungJune/2022-04-15_Kotest%EB%9E%80%3F_week9.md)
> [7기][김형준] Kotest란?

- KimMinSeong/2022-04-21_Java18_Review.md
드디어 마지막 발표네요! 10주동안 많이 배울 수 있었습니다 ㅎㅎ 나머지 회고는 다음주에 길게(?) 작성하겠습니다!
[편하게보기](https://github.com/MINS99/posting-review/blob/KimMinSeong/KimMinSeong/2022-04-21_Java18_Review.md)
> [7기][김민성] Java 18까지의 변화

- minseok/2022-04-20-springOAuthKakao.md
갑자기 일을 시작하는 바람에 포스팅을 급하게 마무리하게 되어 좀 그렇습니다.
마지막 포스팅인데 좀 아쉽네요.
> [7기] [김민석] spring 으로 kakao OAuth 로그인 하기

- yongjukwon/2022-04-21-reflection.md
[편하게 보기](https://github.com/yongjukwon/posting-review/blob/backup/yongjukwon/2022-04-21-reflection.md)
> [7기][권용주]Java Reflection

- tis/2022-04-29/마지막_회고.md
[편하게 보기](https://github.com/this-is-spear/posting-review/blob/tis/tis/2022-04-29/%EB%A7%88%EC%A7%80%EB%A7%89_%ED%9A%8C%EA%B3%A0.md)
> [7기][이건창] 회고

- KimDoubleB/2022-04-29_7th_end.md
[Read](https://github.com/Meet-Coder-Study/posting-review/blob/a0009aedac6267d204fde075a543d9017e72abcc/KimDoubleB/2022-04-29_7th_end.md)
> [7기][김보배] 7기 회고

- hyoungJune/2022-04-29_end_week10.md
[7기 회고](https://github.com/Flamme1004K/posting-review/blob/week4/hyoungJune/2022-04-29_end_week10.md)
> [7기][김형준] 7기 회고

- KimMinSeong/2022-04-28_회고.md
[편하게 보기](https://github.com/MINS99/posting-review/blob/KimMinSeong/KimMinSeong/2022-04-28_%ED%9A%8C%EA%B3%A0.md)
드디어 마지막!!
스터디 참여하면서 정말 많이 배울 수 있었습니다. 감사합니다 🥰
> [7기][김민성] 회고

- pkch93/2022-04-28-7th-retrospective.md
간략하게 블로그 포스팅 7기를 돌아봤습니다..
[편하게보기](https://github.com/Meet-Coder-Study/posting-review/pull/1014/files?short_path=75dfc27#diff-75dfc279cca58967ec5fc2691cd361204bb59d6cbaad0c8095c874f5a2d147d4)
> [7기][박경철] 7기 회고

- .github/auto_assign.yml
asssignee 에 자동으로 pr 생성자를 등록시켜주는 GitHub App 입니다. 있으면 좋을것 같아서 pr 올립니다.
https://github.com/apps/auto-assign
GitHub App을 요 레포에 추가해주는 작업도 필요해요!
> env: auto-assign

- yewon/2022-06-16-RDMA.md
[링크](https://github.com/kyeah01/posting-review/blob/master/yewon/2022-06-16-RDMA.md)
> [8기][강예원] RDMA

- hyoungJune/2022-06-15-리스트에 대한 방어적 복사와 읽기전용-8기-1week.md
[링크](https://github.com/Flamme1004K/posting-review/blob/1week/hyoungJune/2022-06-15-%EB%A6%AC%EC%8A%A4%ED%8A%B8%EC%97%90%20%EB%8C%80%ED%95%9C%20%EB%B0%A9%EC%96%B4%EC%A0%81%20%EB%B3%B5%EC%82%AC%EC%99%80%20%EC%9D%BD%EA%B8%B0%EC%A0%84%EC%9A%A9-8%EA%B8%B0-1week.md)
> [8기][김형준]리스트에 대한 방어적 복사와 읽기전용

- yun/2022-06-16-slueth-fuel.md
[Sleuth 분산 환경 트래킹 With Fuel](https://github.com/cheese10yun/posting-review/blob/master/yun/2022-06-16-slueth-fuel.md)
> [8기][김남윤] Sleuth 분산 환경 트래킹 With Fuel

- GuMinGyu/2022-07-27-test-network-request.md
[편하게 보기](https://github.com/kooku0/posting-review/blob/kooku0/GuMinGyu/2022-07-27-test-network-request.md)
> [8기][구민규] e2e 테스트에서 api mocking 하는게 옳은가?

- hyoungJune/2022-08-10_Test Double과 Stub, Mock 그리고 Fake.md
[미리보기](https://github.com/Flamme1004K/posting-review/blob/week4/hyoungJune/2022-08-10_Test%20Double%EA%B3%BC%20Stub%2C%20Mock%20%EA%B7%B8%EB%A6%AC%EA%B3%A0%20Fake.md)
> [8기][김형준] Test Double과 Stub, Mock 그리고 Fake

- yewon/2022-08-13-NS3.md
[편하게보기](https://github.com/kyeah01/posting-review/blob/master/yewon/2022-08-13-NS3.md)
NS-3 network simulator tutorial을 소개해드립니다!
> [8기][강예원] NS-3 network simulator

- minseok/2022-09-20-Vaadin_intro.md
> [김민석] Vaadin Framework 1편

- GuMinGyu/2022-09-22-테스트코드.md
- 회사에서 팀원과 이야기 나누었던 내용을 조금 다듬어서 적어보았어요.
[편하게 읽기](https://github.com/kooku0/posting-review/blob/kooku0/GuMinGyu/2022-09-22-%ED%85%8C%EC%8A%A4%ED%8A%B8%EC%BD%94%EB%93%9C.md)
> [구민규] 테스트코드 스몰톡

- taekyeom/2022-09-22-module-federation-for-mfa.md
[편하게 읽기](https://github.com/Meet-Coder-Study/posting-review/blob/taekyeom/taekyeom/2022-09-22-module-federation-for-mfa.md)
> [이태겸] MFA를 위한 모듈 페더레이션

- EP/@Transactional 상황별 commit, rollback 전략.md
[편하게 읽기](https://github.com/eastperson/posting-review/blob/master/EP/%40Transactional%20%EC%83%81%ED%99%A9%EB%B3%84%20commit%2C%20rollback%20%EC%A0%84%EB%9E%B5.md)
> [김동인] @Transactional 상황별 commit, rollback 전략

- hyeinkim/2022-10-01-Redisson.md
[편하게 보기](https://github.com/Meet-Coder-Study/posting-review/blob/02c07d7ffd9451972955552a0d37c92ccd2df081/hyeinkim/2022-10-01-Redisson.md)
> [김혜인] Redisson

- len/IDL 을 효과적으로 사용해보기.md
https://github.com/LenKIM/idl-demo-client
관련 저장소
> IDL 중 protobuf 잘 사용하기..!

- 프로젝트1_1.md
다양한 포맷을 주고받을 수 잇는 AJAX와 서버와 통신할 수 있는 라이브러리인 Axios에 대해 다루었습니다!
> [박규성] AJAX와 Axios

- JangAyeon/2022-09-27-JS:FrontEnd-Interview.md
다음주에 스터디에서 모의 면접을 하고 피드백을 갖는 활동이 있어서 이번주는 프론트엔드 면접 질문을 정리하면서 자바스크립트에 대해 공부하는 시간을 가졌습니다. 모의 면접도 열심히 해내고 다음주부터는 원래 했던 타입스크립트 포스팅을 이어나가겠습니다 :)
> [장아연] 프론트엔드 면접 : 자바스크립트 1

- minseok/2022-09-29-Vaadin_layout.md
이번편은 지난번에 이어서 Vaadin 의 레리아웃에 대해서 소개합니다.
> [김민석] Vaadin - layout

- yun/2022-10-08-external-infrastructure-testing.md
[외부 인프라 스트럭처 테스트](https://github.com/cheese10yun/blog-sample/blob/master/tesing/demo/document/external-infrastructure-testing.md)
> [김남윤] 외부 인프라 스트럭처 테스트

- pkch93/2022-09-29-unnessesary-rerendering.md
- pkch93/2022-10-06-react-context-api.md
[편하게 보기](https://github.com/Meet-Coder-Study/posting-review/pull/1105/files?short_path=ea5e8c9#diff-ea5e8c99033f8a19968410706fa0195818b10f9525df60ec3b871a01254e108c)
> [박경철] React Context

- yenowme/swr.md
[편하게 보기](https://github.com/Meet-Coder-Study/posting-review/compare/master...yenowme?quick_pull=1&short_path=059542e#diff-059542e33efb2d34ffe4c272b995d020baa01faf373afa497d62cf550d7f6f1e)
> [정예나] swr을 통한 전역 관리

- minseok/2022-10-05-Vaadin_component.md
> [김민석] Vaadin - Component

- taekyeom/2022-10-13-why-vite.md
[편하게 읽기](https://github.com/Meet-Coder-Study/posting-review/blob/taekyeom/taekyeom/2022-10-13-why-vite.md)
> [이태겸] Vite를 사용해야 하는 이유

- taekyeom/2022-10-27-lazy-evaluation.md
[편하게 읽기](https://github.com/Meet-Coder-Study/posting-review/blob/taekyeom/taekyeom/2022-10-27-lazy-evaluation.md)
> [이태겸] 지연 로딩 (feat. 함수형 프로그래밍)

- pkch93/2022-10-27-feconf2022.md
[편하게 보기](https://github.com/Meet-Coder-Study/posting-review/pull/1123/files?short_path=f9d34d1#diff-f9d34d1f338a878f7724d5fec2b5866895974adce28f351a96024c0bdced6b1a)
> [박경철] 조금 늦은 feconf 2022 후기

- pkch93/2022-11-03-peerDependencies.md
[편하게 보기](https://github.com/Meet-Coder-Study/posting-review/pull/1125/files?short_path=b5cfb84#diff-b5cfb84a664652f6f6ab6b7459c34739577302392a380eb74d59a289c7f5590e)
> [박경철] peerDependencies

- taekyeom/2022-11-03-turbopack-fater-than-vite.md
[편하게 읽기](https://github.com/Meet-Coder-Study/posting-review/pull/1126/files?short_path=7c91bd8#diff-7c91bd89ede65ce26163c3512b959ba2263fffdf887d006662e7e3718ab364af)
> [이태겸] Turbopack은 정말로 Vite 보다 10배 빠른가요?

- taekyeom/2022-11-10-react-start-kit-without-cra.md
[편하게 읽기](https://github.com/Meet-Coder-Study/posting-review/pull/1129/files?short_path=2bbb8f4#diff-2bbb8f4e0772389785c8411563b9116695754bbf75728032458ac3c3a42a0cd0)
> [이태겸] CRA 없이 React 프로젝트 시작하기

- taekyeom/2022-11-17-monorepo_intro.md
[편하게 읽기](https://github.com/Meet-Coder-Study/posting-review/pull/1135/files?short_path=34caca2#diff-34caca26ad5647ecb12439e4c237c5e99564f085bac9a339b75442bf5c94064f)
> [이태겸] monorepo introduction

- pkch93/2022-11-17-monorepo-tools.md
[편하게 보기](https://github.com/Meet-Coder-Study/posting-review/pull/1134/files?short_path=57af216#diff-57af216f56bac1c2ddb911dd626589ac4a7000d314077098e2e1c3d07cb92539)
> [박경철] package manager workspace와 monorepo tools

- mincheolkk/분산락을 이용한 동시성 이슈 해결.md
> [김민철] 분산락을 이용한 동시성 이슈 해결

- pkch93/2023-05-23-kotlin-constants.md
[편하게 보기](https://github.com/Meet-Coder-Study/posting-review/pull/1141/files?short_path=328dfbf#diff-328dfbfb5066c659eac70995f80e49ec8ee13e029b16606c7476b33ff85e9e83)
Java만 주로 써왔었는데 이번에 Kotlin을 학습하고 써보면서 느낀점들을 한번씩 정리하려고 해요~
이번주는 상수 관련해서 작성해보았습니다.
> [박경철] Java 개발자가 배우는 Kotlin - 상수표현하기

- yun/2023-05-24-jacoco.md
[보기](https://github.com/cheese10yun/posting-review/blob/master/yun/2023-05-24-jacoco.md)
> [김남윤] 테스트 커버리지 측정 도구 Jacoco

- EP/JPA Entity 내부에서 이벤트를 발행하려면?.md
[편하게 보기](https://github.com/Meet-Coder-Study/posting-review/pull/1142/files?short_path=e44a546#diff-e44a546d532dd8ec867c1efec07fcfd89053a085600a7fba3e8e9c50abbba4f1)
JPA 엔티티 내부에서 이벤트를 발행하는 방법을 고민하면서 글을 작성해봤습니다.
사실 다른 방법이 있는지 궁금하기도 해서 피드백 환영합니다 😄
> [김동인] JPA Entity 내부에서 이벤트를 발행하려면?

- taekyeom/2023-05-24-effective-react-query-keys.md
[편하게 읽기](https://github.com/Meet-Coder-Study/posting-review/blob/taekyeom/taekyeom/2023-05-24-effective-react-query-keys.md)
최근에 읽고 적용해본 좋은 글이 있어서 소개드립니다.
> [이태겸] 효과적인 React Query Keys 전략

- EunjiShin/2023-05-24-5ways-that-implement-count.md
[편하게 보기](https://hogwart-scholars.tistory.com/entry/Spring-Boot-count%EB%A5%BC-%EA%B5%AC%ED%98%84%ED%95%98%EB%8A%94-5%EA%B0%80%EC%A7%80-%EB%B0%A9%EB%B2%95)
이번 주차에는 무의식적으로 대충 쓰기 쉬운 count 기능에 대해 고민해봤습니다!
포스팅에 있는 방법 외에도 새로운 방법이 있다면 댓글 / PR 코멘트 등으로 알려주세요 😄
+ 이번 기수 부터는 md 대신 블로그 링크를 첨부해도 된다고 들어서 포스트 링크 남깁니다! 
혹시 리뷰하시기 불편하시다면 의견 남겨주세요~~
> [신은지] count를 구현하는 5가지 방법

- tis/2023-05-31/옵시디언활용법.md
오늘은 블로그 글로 공유합니다!
[링크](https://publish.obsidian.md/this-is-spear/%EC%8A%A4%ED%84%B0%EB%94%94+%EC%A0%95%EB%A6%AC/%EB%B0%8B+%EC%BD%94%EB%8D%94+10%EA%B8%B0/2%EC%A3%BC%EC%B0%A8+-+%EC%98%B5%EC%8B%9C%EB%94%94%EC%96%B8+%EC%9E%98+%EC%93%B0%EA%B8%B0)
> [이건창] 옵시디언 활용 방법

- leehajeong/week2/네트워크 기초.md
블로그 링크 : https://big-front-teeth.tistory.com/18
> [이하정] 네트워크 기초

- EP/동시성 이슈의 사례와 트랜잭션 격리수준.md
[편하게 보기](https://github.com/Meet-Coder-Study/posting-review/pull/1159/files?short_path=4164fda#diff-4164fda63dc61bd691443094b96e9baaef264793ce1d1c154498ec0a78ab4bcc)
동시성 이슈의 사례들과 이를 해결하기 위한 트랜잭션 격리수준에 대해서 글을 작성해봤습니다 😄
> [김동인] 동시성 이슈의 사례와 트랜잭션 격리수준

- EunjiShin/2023-05-31-spin-lock.md
[블로그 링크](https://hogwart-scholars.tistory.com/entry/OS-Spin-Lock-%EC%8A%A4%ED%95%80%EB%9D%BD%EC%97%90-%EB%8C%80%ED%95%B4-%EC%95%8C%EC%95%84%EB%B3%B4%EC%9E%90)
지난 밑업 때 채팅에서 주워들은 스핀락에 대해 공부해봤습니다 🚀
> [신은지] Spinlock(스핀락)에 대해 알아보자

- jgjgill/2023-05-31-learn-about-ecma2023.md
안녕하세요. 👋 최근 ECMA 2023에 대한 글들을 많이 봐서 저도 정리하는 시간을 가졌습니다. 🙇‍♂️
[블로그에서 보기](https://jgjgill-blog.netlify.app/blog/learn-about-ecma2023/)
[편하게 보기](https://github.com/jgjgill/posting-review/blob/jgjgill/jgjgill/2023-05-31-learn-about-ecma2023.md)
> [이종길] ECMA2023에 대해 알아보기 - 배열 메서드 중심으로

- yun/2023-05-31-intellij-tip.md
[보기](https://github.com/cheese10yun/posting-review/blob/master/yun/2023-05-31-intellij-tip.md)
> [김남윤] 인텔리제이 다양한 팁

- pkch93/2023-05-29-kotlin-constructor.md
[편하게 보기](https://github.com/Meet-Coder-Study/posting-review/pull/1161/files?short_path=95a074f#diff-95a074f125fcf67db5a70b038cb3c04de06e975bf11b206fb8282b44c48bb3bb)
이번엔 Kotlin의 생성자에 대해 알아보았습니다.
> [박경철] Java 개발자가 배우는 Kotlin - 생성자

- sangwon/2023-05-31-singleton-container.md
[보기](https://github.com/Meet-Coder-Study/posting-review/pull/1168/files?short_path=59867f7#diff-59867f7db8aefe2ebc1ea6bcc190be70a0bb24bc176deb242c62f5d16782b710)
김영한님 스프링 핵심 원리를 2회독 하면서 간단하게 스프링이 싱글톤 컨테이너를 사용한 이유에 대해 정리해 보았습니다.
> [이상원] 스프링 싱글톤 컨테이너

- taekyeom/2023-05-31-compound-component.md
[편하게 읽기](https://github.com/Meet-Coder-Study/posting-review/blob/taekyeom/taekyeom/2023-05-31-compound-component.md)
변경에 유연한 컴포넌트 개발에 대한 고민하다가 찾아보고 적용하는데 도움이 되었던 글에 대해 소개드릴려고 합니다.
> [이태겸] Compound Component Pattern

- mincheolkk/AOP를 활용한 공통 기능 구현.md
블로그 링크로 공유합니다 :)
[블로그 링크](https://more-n.tistory.com/9)
> [김민철] AOP를 활용한 공통 기능 구현

- yun/2023-06-07-nontile.md
[보기](https://github.com/cheese10yun/posting-review/blob/master/yun/2023-06-07-nontile.md)
> [김남윤] 개발을 하면서 이것 저것 정리

- 2023-06-07-only_full_group_by-mysql.md
[편하게 보기](https://github.com/Meet-Coder-Study/posting-review/commit/7104fedb36a4e43e925c31a35a1def4b33f77caa)
mysql 사용하면서 발생한 트러블 슈팅을 작성해보았습니다.
> [남혜민] MySQL only_full_group_by 모드

- EunjiShin/2023-06-07-kotlin-study-1.md
[편하게 보기](https://hogwart-scholars.tistory.com/entry/Kotlin-%EC%BD%94%ED%8B%80%EB%A6%B0%EC%9D%84-%EC%8C%88%EC%8B%B8%EB%A8%B9%EC%96%B4-%EB%B3%B4%EC%9E%90-1)
코틀린 고수가 되는 그 날까지..!
> [신은지] 코틀린 쌈싸먹기

- mincheolkk/OSIV 설정 변경과 개선과정.md
OSIV에 관한 글을 작성했습니다 :)
[블로그에서 보기](https://more-n.tistory.com/10)
> [김민철] OSIV 설정 변경과 개선과정

- jgjgill/2023-06-07-learn-about-reference-copy.md
`structuredClone`에 대해 알게 되면서 참조 복사를 정리하는 글을 작성했습니다. 🙇‍♂️
[블로그에서 보기](https://jgjgill-blog.netlify.app/blog/development/)
[편하게 보기](https://github.com/jgjgill/posting-review/blob/jgjgill/jgjgill/2023-06-07-learn-about-reference-copy.md)
> [이종길] 참조 복사에 대해 알아보기

- pkch93/2023-06-05-SAM-convention.md
[편하게 보기](https://github.com/Meet-Coder-Study/posting-review/pull/1182/files?short_path=5e15112#diff-5e15112f5b5e0c1570c399af6f457314c2b1a34ebf3583e1bafdbc93ed9297ac)
이번에는 Functional Interface에 대해 알아보았어요.
> [박경철] Java 개발자가 배우는 Kotlin - Functional Interface

- leehajeong/week4/OSI 7계층.md
https://big-front-teeth.tistory.com/19
https://big-front-teeth.tistory.com/20
분명 쓸 때는 이해가 가서 썼는데 포스팅 직전 올라가서 다시 보면 
겉잡을 수 없이 커진 개념들을 놓치고 있는 나 자신이 보인다
> [이하정] OSI 7계층

- pkch93/2023-06-14-kotlin-properties.md
[편하게 보기](https://github.com/Meet-Coder-Study/posting-review/pull/1194/files?short_path=7a2581d#diff-7a2581d704c71f89f4740cbe3fe0b73ad55a4adce541fb0c4db0790e7958150b)
이번에는 Kotlin의 프로퍼티에 대해 알아보았어요
> [박경철] Java 개발자가 배우는 Kotlin - 프로퍼티

- EunjiShin/2023-06-14-crawl-og-tag-with-jsoup.md
[편하게 보기](https://hogwart-scholars.tistory.com/entry/Spring-Boot-Jsoup%EC%9C%BC%EB%A1%9C-OG%ED%83%9C%EA%B7%B8-%EB%A9%94%ED%83%80-%EB%8D%B0%EC%9D%B4%ED%84%B0-%ED%81%AC%EB%A1%A4%EB%A7%81%ED%95%98%EA%B8%B0)
자바로는 처음 크롤링해보는데, 생각보다 사용하기 쉽더군요? 😄
익숙해지면 재밌는 걸 많이 해 볼 수 있을 것 같아요! :)
> [신은지] Jsoup으로 OG태그 메타 데이터 크롤링하기

- EunjiShin/2023-06-21-rate-limiters-on-spring-boot-and-java.md
[편하게 보기](https://hogwart-scholars.tistory.com/entry/Spring-Boot-%EC%9E%90%EB%B0%94-%EC%8A%A4%ED%94%84%EB%A7%81%EC%97%90%EC%84%9C-%EC%B2%98%EB%A6%AC%EC%9C%A8-%EC%A0%9C%ED%95%9C-%EA%B8%B0%EB%8A%A5%EC%9D%84-%EA%B5%AC%ED%98%84%ED%95%98%EB%8A%94-4%EA%B0%80%EC%A7%80-%EB%B0%A9%EB%B2%95)
아슬아슬하게 세이프^___^
> [신은지] Java Spring에서 처리율 제한 기능을 구현하는 4가지 방법

- jgjgill/2023-06-21-learn-about-dom.md
`DOM`과 관련된 용어로 `Node`와 `Element`에 대해 정리하는 글을 작성했습니다. 🙇‍♂️
[블로그에서 보기](https://jgjgill-blog.netlify.app/blog/learn-about-dom)
[편하게 보기](https://github.com/jgjgill/posting-review/blob/jgjgill/jgjgill/2023-06-21-learn-about-dom.md)
> [이종길] DOM과 친해지기

- pkch93/2023-06-20-kotlin-equals.md
[편하게 보기](https://github.com/Meet-Coder-Study/posting-review/pull/1203/files?short_path=1dd2119#diff-1dd2119b871ac7504bc01e937454ec806d6b1a3db7a0b70b343819501ff6e7f1)
생각보다 길지 않고 간단하게 적혔네요 ㅎㅎ
> [박경철] Java 개발자가 배우는 Kotlin - 동등성 비교

- EunjiShin/2023-06-28-auto-increment-pk-hide.md
밑코더 여러분들은 실제 회사 또는 프로젝트에서 어떻게 PK를 다루시는지 궁금하네요 🤔
고냥 삼삼하게 재밌는거 한 번 해봤다고 봐주시면 감사하겠습니다! ^.^
[편하게 보기](https://hogwart-scholars.tistory.com/entry/Spring-Boot-Auto-Increment-PK-Id%EB%A5%BC-%EB%85%B8%EC%B6%9C%ED%95%98%EC%A7%80-%EC%95%8A%EC%9C%BC%EB%A9%B4%EC%84%9C-API%EC%97%90-%ED%99%9C%EC%9A%A9%ED%95%98%EB%8A%94-%EB%B0%A9%EB%B2%95)
> [신은지] Auto Increment PK Id를 노출하지 않으면서 API에 활용하는 방법

- mincheolkk/@OneToOne 관계에서 지연로딩.md.
지각 제출합니다!
일대일 양방향 관계에서 지연로딩에 관한 글을 작성했습니다 :)
[블로그에서 보기](https://more-n.tistory.com/19)
> [김민철] @OneToOne 관계에서 지연로딩

- jgjgill/2023-06-28-css-in-ts-vanilla-extract.md
`vanilla-extract`에 대해 알게되면서 학습한 글입니다. 🙇‍♂️
[블로그에서 보기](https://jgjgill-blog.netlify.app/blog/css-in-ts-vanilla-extract/)
[편하게 보기](https://github.com/jgjgill/posting-review/blob/jgjgill/jgjgill/2023-06-28-css-in-ts-vanilla-extract.md)
> [이종길] CSS에 타입을 입히다 (vanilla-extract)

- pkch93/2023-06-27-kotlin-generics.md
[편하게 보기](https://github.com/Meet-Coder-Study/posting-review/pull/1215/files?short_path=91fe509#diff-91fe5098c21e8d713b03114168d21d7f30f6ac00a16e72566a21bde06423e0e0)
이번엔 Kotlin의 제네릭에 대해 정리했어요~
> [박경철] Java 개발자가 배우는 Kotlin - Generics

- sangwon/2023-06-28-python-basic.md
파이썬을 처음 배워야하는 일이 생겨서 파이썬에 대해 추천 받은 기본 강의를 정리하고 있습니다.
[보기](https://github.com/Meet-Coder-Study/posting-review/pull/1218/commits/cb31d3deff25d376e4a9c495a8e97e4f85c7df25?short_path=6694ceb#diff-6694ceb00f84b884a87c52f892b7dfc58128f77b3ded6632f7213d519f5247b2)
> [이상원] 파이썬 기초 - 정수, 문자열, Iterable

- yun/2023-06-25-node-install.md
[보기](https://github.com/cheese10yun/posting-review/blob/master/yun/2023-06-25-node-install.md)
> [김남윤] nvm 으로 node version manager 으로 노드 버전 관리

- tis/2023-07-05/코루틴을 배우기전 간단한 학습.md
간단하게 정리한 내용 공유드립니다.
[편하게 보기](https://github.com/this-is-spear/posting-review/blob/master/tis/2023-07-05/%EC%BD%94%EB%A3%A8%ED%8B%B4%EC%9D%84%20%EB%B0%B0%EC%9A%B0%EA%B8%B0%EC%A0%84%20%EA%B0%84%EB%8B%A8%ED%95%9C%20%ED%95%99%EC%8A%B5.md)
조금 더 많은 내용은 아래 블로그에 정리했습니다.
[책 정리 내용 보기](https://publish.obsidian.md/this-is-spear/%EC%8A%A4%ED%84%B0%EB%94%94+%EC%A0%95%EB%A6%AC/%EC%BD%94%EB%A3%A8%ED%8B%B4+%EC%8A%A4%ED%84%B0%EB%94%94/contents/1.+Hello+Concurrent+World!)
> [이건창] 코루틴을 배우기전 간단한 학습

- yun/2023-06-11-좋은 코드 설계를 위한 답없는 고민들.md
- yun/2023-07-02-exposed-3.md
[보기](https://github.com/cheese10yun/posting-review/blob/master/yun/2023-07-02-exposed-3.md)
> [김남윤] Kotlin 기반 경량 ORM Exposed 추가 정리 part 3

- EunjiShin/2023-07-12-facade-pattern.md
[편하게보기](https://hogwart-scholars.tistory.com/entry/Design-Pattern-Facade-%ED%8C%A8%ED%84%B4%EA%B3%BC-%EC%9D%B4%EB%AA%A8%EC%A0%80%EB%AA%A8)
10기 마지막 포스팅 모두 고생하셧습니다!! 🥳
> [신은지] Facade pattern의 이모저모

- minenam/2023-07-12-AWS-Lambda-and-AWS-SAM.md
[편하게 보기](https://github.com/Meet-Coder-Study/posting-review/commit/8d36c4995b7a66ba1c2e54f350ed8638b757877d)
*SAM에 대해서 추후 보완 예정
> [남혜민] AWS Lambda & AWS SAM

- EP/Kotlin의 check()와 require().md
[편하게 보기](https://github.com/eastperson/posting-review/blob/master/EP/Kotlin%EC%9D%98%20check()%EC%99%80%20require().md)
> [김동인] Kotlin의 check()와 require()

- EunjiShin/2023-11-04-AOP-and-Spring-AOP.md
- [편하게 보기](https://hogwart-scholars.tistory.com/entry/Spring-Boot-AOP%EC%99%80-Spring-AOP%EB%A5%BC-%EB%9C%AF%EC%96%B4%EB%B3%B4%EC%9E%90-feat-Proxy)
> [신은지] AOP와 Spring AOP를 뜯어보자 (feat. Proxy, @Transactional)

- jonghyun/2023-11-03-ServiceQuota-Comparison.md
boto3를 활용한 Service Quota 모든 증설이력 확인하기
[+] [Blog Link](https://anggeum.tistory.com/entry/AWS-boto3%EB%A5%BC-%ED%99%9C%EC%9A%A9%ED%95%9C-Service-Quota-%EB%AA%A8%EB%93%A0-%EC%A6%9D%EC%84%A4%EC%9D%B4%EB%A0%A5-%ED%99%95%EC%9D%B8%ED%95%98%EA%B8%B0)
> [이종현]boto3를 활용한 AWS Service Quota 모든 증설이력 확인하기

- hyoungJune/2023-11-03-feature-toggle이란?.md
> [김형준] feature-toggle이란?

- juhyeong/2023-11-01-[Docker-MySQL] Master-Slave Replication(복제) 구축하기.md
https://github.com/Meet-Coder-Study/posting-review/pull/1237 해당 브렌치가 2주 차 작업과 얽혀서 1주 차 재 PR 올립니다.
[편하게 보기](https://github.com/dkswnkk/posting-review/blob/2023-11-01/juhyeong/2023-11-01-%5BDocker-MySQL%5D%20Master-Slave%20Replication(%EB%B3%B5%EC%A0%9C)%20%EA%B5%AC%EC%B6%95%ED%95%98%EA%B8%B0.md)
> [안주형] [Docker-MySQL] Master-Slave Replication(복제) 구축하기

- juhyeong/2023-11-06-[Docker MySQL] Orchestrator를 이용한 High Availability(HA) 구축하기.md
[편하게 보기](https://github.com/dkswnkk/posting-review/blob/2023-11-06/juhyeong/2023-11-06-%5BDocker%20MySQL%5D%20Orchestrator%EB%A5%BC%20%EC%9D%B4%EC%9A%A9%ED%95%9C%20High%20Availability(HA)%20%EA%B5%AC%EC%B6%95%ED%95%98%EA%B8%B0.md)
> [안주형] [Docker-MySQL] Orchestrator를 이용한 High Availability(HA) 구축하기

- yun/2023-10-28-page-query-performance.md
* [보기](https://github.com/cheese10yun/posting-review/blob/master/yun/2023-10-28-page-query-performance.md)
* 이전에 포스팅한 내용에서 Spring Data MongoDB에서도 사용방법을 추가 했습니다.
> [김남윤] JPA 페이징 Performance 향상 방법

- EP/Soft Delete vs Hard Delete.md
- [편하게보기](https://github.com/Meet-Coder-Study/posting-review/blob/ccb68e64207252823a9b97371f803cff21f7cab6/EP/Soft%20Delete%20vs%20Hard%20Delete.md)
> [김동인] Soft Delete vs Hard Delete

- yun/2023-11-06-mongo-repository.md
[보기](https://github.com/cheese10yun/posting-review/blob/master/yun/2023-11-06-mongo-repository.md)
> [김남윤] Spring Data MongoDB Repository 확장

- BeomSeog/2023-11-10-No-thread-bound-request-found.md
[바로가기](https://tommykim.tistory.com/80)
OAuth2를 사용해 소셜로그인 구현중 마주했던 에러에 대해서 발생하게된 이유와 해결법을 적어보았습니다.
> [김범석] No thread-bound request found 예외 발생 이유와 해결법

- jonghyun/2023-11-10-Get_GroupLevel_Memory_Metric_via_CloudwatchAgent.md
Link: https://anggeum.tistory.com/entry/AWS-CloudWatch-agent%EB%A5%BC-%ED%86%B5%ED%95%9C-Group-%EB%A0%88%EB%B2%A8-%EB%A9%94%EB%AA%A8%EB%A6%AC-%EB%A9%94%ED%8A%B8%EB%A6%AD-%EA%B4%80%EC%B0%B0%ED%95%98%EA%B8%B0
> [AWS] CloudWatch agent를 통한 Group 레벨 메모리 메트릭 관찰하기

- JinoBae/2023-11-10-typescript-small-tips.md
- [편하게 보기](https://blex.me/@baealex/typescript-small-tips)
- 타입스크립트 컨벤션을 만들 예정이라, 제가 생각하는 좋은 코드와 그렇게 생각하는 이유를 정리하고자 이 글을 작성했습니다.
> [배진오] 소소한 타입스크립트 팁

- EunjiShin/2023-11-10-class-cohension-and-etc.md
- [편하게 보기](https://hogwart-scholars.tistory.com/entry/%ED%81%B4%EB%A6%B0-%EC%BD%94%EB%93%9C-%EC%99%84%EC%A0%84-%EC%83%9D%EC%84%B1%EC%9E%90%EC%99%80-%EA%B0%92-%EA%B0%9D%EC%B2%B4%EB%A1%9C-%EC%95%88%EC%A0%84%ED%95%98%EA%B2%8C-%ED%81%B4%EB%9E%98%EC%8A%A4-%EA%B4%80%EB%A6%AC%ED%95%98%EA%B8%B0)
> [신은지] 클래스 응집도의 중요성, 그리고 완전 생성자와 값 객체

- jonghyun/2023-11-18-ECS Capacity Provider - Deep Dive(1).md
ECS Capcity Provider에 대한 이해한 내용 정리글입니다.
- [Link](https://anggeum.tistory.com/entry/ECS-ECS-Capacity-Provider-Deep-Dive-1)
> [이종현] ECS Capacity Provider - Deep Dive (1).md

- juhyeong/2023-11-13-[Docker MySQL] Proxy Layer 구축하기.md
👉 [깃허브에서 보기](https://github.com/dkswnkk/posting-review/blob/2023-11-13/juhyeong/2023-11-13-%5BDocker%20MySQL%5D%20Proxy%20Layer%20%EA%B5%AC%EC%B6%95%ED%95%98%EA%B8%B0.md)
👉 [티스토리로 보기](https://dkswnkk.tistory.com/729)
> [안주형] [Docker-MySQL] Proxy Layer 구축하기

- EunjiShin/2023-11-17-first-class-collection.md
- [편하게 보기](https://hogwart-scholars.tistory.com/entry/Java-%EC%9D%BC%EA%B8%89-%EC%BB%AC%EB%A0%89%EC%85%98-First-Class-Collection)
- 객체지향 책이나 클린코드 책에 자주 나오는 일급 컬렉션에 대해 정리해봤습니다. 코드에도 실제로 적용할 수 있게 노력하려구요 💪
> [신은지] 일급 컬렉션에 대하여

- yun/2023-11-16-mongo-test-data-setup.md
[MongoDB 다양한 테스트 케이스를 커버할 수 있는 테스트 데이터 셋업 방법](https://github.com/cheese10yun/posting-review/blob/master/yun/2023-11-16-mongo-test-data-setup.md)
> [김남윤 ]MongoDB 다양한 테스트 케이스를 커버할 수 있는 테스트 데이터 셋업 방법

- jonghyun/[이종현] ECS Capacity Provider - (2).md
ECS Capacity Provider 도입 검토에 있어 기능분석한 내용입니다.
- [블로그 링크](https://anggeum.tistory.com/entry/ECS-ECS-Capacity-Provider-Deep-Dive-1)
> [이종현] ECS Capacity Provider - (2).md

- juhyeong/2023-11-24-[Spring] 다중 인스턴스 환경에서 단일 스케줄러 동작 보장하기.md
👉 [깃허브에서 보기](https://github.com/dkswnkk/posting-review/blob/2023-11-24/juhyeong/2023-11-24-%5BSpring%5D%20%EB%8B%A4%EC%A4%91%20%EC%9D%B8%EC%8A%A4%ED%84%B4%EC%8A%A4%20%ED%99%98%EA%B2%BD%EC%97%90%EC%84%9C%20%EB%8B%A8%EC%9D%BC%20%EC%8A%A4%EC%BC%80%EC%A4%84%EB%9F%AC%20%EB%8F%99%EC%9E%91%20%EB%B3%B4%EC%9E%A5%ED%95%98%EA%B8%B0.md)
👉 [티스토리로 보기](https://dkswnkk.tistory.com/731)
> [안주형] 다중 인스턴스 환경에서 단일 스케줄러 동작 보장하기 - Spring

- EunjiShin/2023-11-24-java-reference-type-comparison.md
- [편하게보기](https://hogwart-scholars.tistory.com/entry/Java-%EC%B0%B8%EC%A1%B0-%ED%83%80%EC%9E%85%EC%97%90%EC%84%9C-%EB%8F%99%EB%93%B1%EC%84%B1-%ED%8C%90%EB%8B%A8%ED%95%98%EA%B8%B0-feat-String-Pool-Integer-cache)
- `Integer number = 1`과 `Integer number2 = 1`가 있을 때, `number == number2`는 true일까요 false일까요? 정답은 포스트에 있습니다 🤩
> [신은지] 자바의 참조 타입에서 동등성 판단하기

- SeheeLee01/2023-11-10-spring-https.md
블로그: [[Spring Security] FilterChainProxy와 HTTPS, 스프링에서 알아보기](https://medium.com/@Hailey24/spring-security-filterchainproxy%EC%99%80-https-%EA%B4%80%EB%A0%A8-%EC%95%94%ED%98%B8%ED%99%94-fe291aa4c4b3)
저번 주와 이번 주는 부트캠프와 다른 이슈들이 많이 겹쳐서 좀 더 정성스레 쓰지 못했습니다...🥲
벌써 마지막 주인데 그래도 이렇게 여러 번 블로그를 쓰다 보니 글을 어떻게 하면 더 효과적으로 쓸 수 있을지 고민도 해보고, 정확한 정보를 전달하기 위해서 많이 찾아보고 그랬던 것 같아요! 
좋은 경험 해볼 수 있어서 좋았던 것 같습니다! :)
> [이세희] Spring Security와 HTTPS

- JinoBae/2023-11-17-angular-standalone-component.md
- JinoBae/2023-11-25-angular-pipe.md
- [편하게 보기](https://blex.me/@baealex/angular-pipe)
- 앵귤러의 파이프에 대해서 작성하였습니다. 혼란스러웠던 순수 파이프와 비순수 파이프를 중심으로 적었습니다.
#1277 3주차 PR이 머지되지 않아서 4주차 커밋이 3주차 PR로 들어가서 클로즈하고 다시 PR 올립니다 🙇
>  [배진오] Angular :: Pipe

- SeYunKim/2024-01-06-Introduction to Ruby on Rails Patterns and Anti-patterns.md
[편하게 보기](https://rutgo-letsgo.tistory.com/380)
> [김세윤] Introduction to Ruby on Rails Patterns and Anti-patterns (Ruby On Rails의 패턴과 안티패턴 소개)

- naayoungkwon/2024-01-13-spring-osiv.md
[velog 링크](https://velog.io/@kny8092/%EC%98%81%EC%86%8D%EC%84%B1%EC%9D%80-Transactional-%EC%97%90%EC%84%9C%EB%A7%8C-%EC%9C%A0%EC%A7%80%EB%90%A0%EA%B9%8C)
> [권나영] 영속성은 @Transactional 에서만 유지될까

- Dongmin/2024-01-09-얕은 복사와 깊은 복사에 대해 알아보자!.md
[편하게보기](https://velog.io/@mindong2/%EC%96%95%EC%9D%80-%EB%B3%B5%EC%82%AC%EC%99%80-%EA%B9%8A%EC%9D%80-%EB%B3%B5%EC%82%AC%EC%97%90-%EB%8C%80%ED%95%B4-%EC%95%8C%EC%95%84%EB%B3%B4%EC%9E%90)
> [김동민] 얕은 복사와 깊은 복사에 대해 알아보자!

- geuno/2024-01-11-Gradle-multi-project-build.md
[ 글 바로가기 ](https://github.com/hymn-fly/posting-review/blob/2d63b526751c9f957368aeb1340321c5dc771a13/geuno/2024-01-11-Gradle-multi-project-build.md)
> [길근오] Gradle Multi Project Build 구성 경험기

- youMe/2024-01-11-Ch01_Refactoring_A first_example.md
[블로그 보기](https://fillbycoding.tistory.com/99)
> [조유미] Chapter 01. Refactoring : A first_example (리팩터링: 첫 번째 예시)

- yun/2024-01-13-mongo-update-performance.md
[MongoDB Update 성능 측정 및 분석](https://github.com/cheese10yun/posting-review/blob/master/yun/2024-01-13-mongo-update-performance.md)
> [김남윤] MongoDB Update 성능 측정 및 분석

- naayoungkwon/2024-01-20-rate-limiter.md
[velog link](https://velog.io/@kny8092/%EC%B2%98%EB%A6%AC%EC%9C%A8-%EC%A0%9C%ED%95%9C-%EC%9E%A5%EC%B9%98-%EB%B6%99%EC%9D%B4%EA%B8%B0-%EC%97%AC%EC%A0%95)
> [권나영] 처리율 제한 장치 붙이기 여정

- geuno/2024-01-19-test-container-mssql.md
[링크](https://github.com/hymn-fly/posting-review/blob/master/geuno/2024-01-19-test-container-mssql.md)
> [길근오] Spring Boot Test Container 도입기

- Dongmin/2024-01-19-클로저 너는 누구니.md
[편하게보기](https://velog.io/@mindong2/%ED%81%B4%EB%A1%9C%EC%A0%80-%EB%84%88%EB%8A%94-%EB%88%84%EA%B5%AC%EB%8B%88)
> add 2024-01-19-클로저! 너는 누구니?

- taejung/2024-01-18-dart-hashmap-splaytreemap-linkedhashmap.md
https://cloud-whale.hashnode.dev/dart-hashmap-splaytreemap-linkedhashmap
> [12] [허태정] [Dart] Map 구현체: HashMap, SplayTreeMap, LinkedHashMap

- kimwoocheol/2024-01-15-UI-의존-개발-지양.md
[링크](https://github.com/jikimee64/posting-review/blob/c715a9bcd47ee969398bf25bf1832be3131e21d4/kimwoocheol/2024-01-15-UI-%EC%9D%98%EC%A1%B4-%EA%B0%9C%EB%B0%9C-%EC%A7%80%EC%96%91.md)
> [김우철] UI 의존 개발 지양

- tis/2024-01-20/javaagent.md
[편하게 보기](https://github.com/this-is-spear/posting-review/blob/tis/2024-01-20/tis/2024-01-20/javaagent.md)
> [이건창] Javaagnet 학습

- SeYunKim/Ruby on Rails View Patterns and Anti-patterns.md
[편하게 보기](https://rutgo-letsgo.tistory.com/entry/%EB%B2%88%EC%97%AD-Ruby-on-Rails-View-Patterns-and-Anti-patterns)
> [김세윤] Ruby on Rails View Patterns and Anti-patterns

- yun/2024-01-27-springboot3-jpa-querydsl.md
[보기](https://github.com/cheese10yun/posting-review/blob/master/yun/2024-01-27-springboot3-jpa-querydsl.md)
> [김남윤] Spring Boot3 Kotlin JPA & Querydsl 적용하기

- naayoungkwon/2024-01-26-functional-programming-in-java.md
[velog 링크](https://velog.io/@kny8092/%EC%9E%90%EB%B0%94%EC%9D%98-%ED%95%A8%EC%88%98%ED%98%95)
> [권나영] 함수형 인터페이스 in Java

- kimwoocheol/2024-01-26 Jpa save vs saveAndFlush vs saveAll.md
[링크](https://dncjf64.tistory.com/458)
> [김우철] Jpa save vs saveAndFlush vs saveAll

- naayoungkwon/2024-02-03-spring-aop.md
[링크](https://velog.io/@kny8092/%ED%94%84%EB%A1%9D%EC%8B%9C%EC%99%80-AOP)
> [권나영] Spring AOP

- SeYunKim/2024-02-03-[번역] General Ruby on Rails Problems and Takeaways(일반적인 Ruby On Rails 문제 및 해결방법).md
- SeYunKim/2024-02-03-[번역] Ruby on Rails Controller Patterns and Anti-patterns(Ruby On Rails의 컨트롤러의 패턴과 안티패턴).md
[편하게보기1](https://rutgo-letsgo.tistory.com/entry/%EB%B2%88%EC%97%AD-Ruby-on-Rails-Controller-Patterns-and-Anti-patterns)
[편하게보기2](https://rutgo-letsgo.tistory.com/entry/%EB%B2%88%EC%97%AD-General-Ruby-on-Rails-Problems-and-Takeaways%EC%9D%BC%EB%B0%98%EC%A0%81%EC%9D%B8-Ruby-On-Rails-%EB%AC%B8%EC%A0%9C-%EB%B0%8F-%ED%95%B4%EA%B2%B0%EB%B0%A9%EB%B2%95)
> [김세윤] Ruby On Rails Controller Patterns and Anti-patterns / General Ruby on Rails Problems and Takeaways

- taejung/2024-02-03-why-value-object.md
https://aqudi.me/why-value-object
2월 3일 때 발표를 했었는데 올리는 게 좀 늦었습니다.
> [허태정] Value Object를 통한 안전한 데이터 사용

- joeun/2024-10-01-nmap-host-discovery.md
- 포트 스캐닝 최적화 기법 중 Host Discovery에 대한 내용을 찾아봤습니다.
- [블로그 보기](https://medium.com/@eeunjo/nmap으로-알아보는-포트-스캐닝-0d7906b288f6)
> [김조은] Nmap으로 알아보는 포트 스캐닝: Host Discovery

- jiaekim/2024-10-01-coroutine.md
- jiaekim/2024-10-09-feign-reactive.md
[편하게 보기](https://github.com/jiaekim123/posting-review/blob/master/jiaekim/2024-10-01-coroutine.md)
> [김지애] 코루틴(coroutine) 이란?

- S0okJu/2024-10-01-openstack-setup-and-network-problems.md
- S0okJu/2024-10-09-project-final-review.md
- [블로그 보기](https://s0okju.github.io/p/server-setup-4/)
> [김다경] 서버 구축기 - 4. Kolla-ansible 설치 시 마주한 네트워크 문제

- yerimkim/2024-10-02-세마포어-활용-사례.md
- yerimkim/2024-10-09-네트워크-장비-IP주소-Routing.md
[세마포어 활용 사례](https://velog.io/@kiel0103/%EC%84%B8%EB%A7%88%ED%8F%AC%EC%96%B4-%ED%99%9C%EC%9A%A9-%EC%82%AC%EB%A1%80)
> [김예림] 세마포어 활용 사례

- ghghtygh/2024-10-02-hierarchical-table.md
- [편하게 보기](https://github.com/ghghtygh/posting-review/blob/18a18cd4500e093c440ad70df5555dbc73fe276f/ghghtygh/2024-10-02-hierarchical-table.md)
-  MySQL 계층형 테이블 종류와 쿼리 성능에 대한 포스팅입니다.
> [나주현] MySQL 계층형 테이블 설계 및 쿼리 성능 분석

- Jogeonsang/2024-10-02-type-safe-and-reliable.md
[블로그](https://www.marcus-log.dev/posts/type-safe-and-reliable)
현재 우리가 작성하는 코드에 타입을 정말 신뢰할 수 있는지 의문을 던지고 프론트엔드 영역에서 가장 많은 데이터 영역을 다루는 API Response에 대해서 100% 신뢰할 수 있는 코드로 만드는 방법에 대해서 소개합니다.
> [조건상] Type-safe 그리고 Reliable

- yerimkim/2024-10-09-네트워크-장비-IP주소-Routing.md
- yerimkim/2024-10-15-CORS-정리.md
[네트워크 장비, IP주소, 라우팅](https://velog.io/@kiel0103/%EB%84%A4%ED%8A%B8%EC%9B%8C%ED%81%AC-%EC%9E%A5%EB%B9%84-%EB%B0%8F-%EC%97%B0%EA%B2%B0-%EA%B5%AC%EC%A1%B0)
> [김예림] 네트워크 장비, IP주소, 라우팅

- yun/2024-10-09-locust.md
- yun/2024-10-16-coroutine-flow.md
[보기](https://github.com/cheese10yun/posting-review/blob/master/yun/2024-10-09-locust.md)
> [김남윤] locust API 성능 테스트 도구

- yerimkim/2024-10-15-CORS-정리.md
[CORS 정리](https://velog.io/@kiel0103/CORS-%EC%A0%95%EB%A6%AC)
> [김예림] CORS 정리

- [안형수] Java GC의 동작원리
[포스팅 보기](https://gudtn0915.tistory.com/3)
> [안형수] Java GC 동작원리

- joeun/2024-10-09-nmap-version-detection.md
- [편하게 보기](https://medium.com/@eeunjo/nmap%EC%9C%BC%EB%A1%9C-%EC%95%8C%EC%95%84%EB%B3%B4%EB%8A%94-%ED%8F%AC%ED%8A%B8-%EC%8A%A4%EC%BA%90%EB%8B%9D-a595ca058f9e)
> [김조은] Nmap으로 알아보는 포트 스캐닝: Service and Application Version Detection

- yerimkim/2024-10-30-EC2로-K8s-클러스터-구성하기.md
[EC2로 K8s 클러스터 구성하기](https://velog.io/@kiel0103/EC2%EB%A1%9C-K8s-%ED%81%B4%EB%9F%AC%EC%8A%A4%ED%84%B0-%EA%B5%AC%EC%84%B1%ED%95%98%EA%B8%B0)
> [김예림] EC2로 K8s 클러스터 구성하기

- S0okJu/2024-10-23-terraform-workspace.md
- S0okJu/2024-10-30-vlan.md
- [블로그 보기](https://s0okju.github.io/p/cloud-network-1/)
> [김다경] 클라우드와 VLAN

- doooo/multi-thread-intellij-debug.md
[링크](https://velog.io/@doogang/intelliJ-%EB%A9%80%ED%8B%B0%EC%8A%A4%EB%A0%88%EB%93%9C-%ED%99%98%EA%B2%BD-debug)
> [박두원] intelliJ 멀티스레드 debug
